name: Build GCC 15 with pre-built glibc

on:
  workflow_dispatch:
  push:

env:
  PREFIX: /data/local/tmp/gnu
  SYSROOT: /data/local/tmp/Android-tools/usr/ld
  TARGET: aarch64-linux-gnu
  JOBS: 4

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential g++ make gawk bison flex texinfo gettext \
            git curl libgmp-dev libmpfr-dev libmpc-dev libisl-dev \
            zlib1g-dev pkg-config python3

      - name: Setup directories
        run: |
          sudo mkdir -p /data/local/tmp
          sudo chown -R $USER:$USER /data/local/tmp
      - uses: actions/checkout@v4
      - name: Debug ld.tar.gz 是否存在
        run: |
          ls -lh ld.tar.gz || { echo "❌ ld.tar.gz 不存在"; exit 1; }
          file ld.tar.gz
      - name: Extract & locate real SYSROOT
        run: |
          sudo mkdir -p /data/local/tmp/Android-tools
          sudo chown -R $USER:$USER /data/local/tmp/Android-tools
          tar -xzf ld.tar.gz -C /data/local/tmp/Android-tools
          REAL_SYSROOT=$(find /data/local/tmp/Android-tools -name 'ld-linux-aarch64.so.*' -printf '%h\n' | head -n1)
          echo "REAL_SYSROOT=$REAL_SYSROOT" >> $GITHUB_ENV
          ls -l "$REAL_SYSROOT"/ld-linux-aarch64.so.*
      - name: Clone GCC
        run: |
          cd /data/local/tmp
          git clone --depth=1 -b master git://gcc.gnu.org/git/gcc.git

      - name: Build GCC
        run: |
          cd /data/local/tmp
          mkdir build-gcc && cd build-gcc
          ../gcc/configure \
            --prefix=$PREFIX \
            --target=$TARGET \
            --with-sysroot=$SYSROOT \
            --enable-languages=c,c++,lto \
            --enable-threads=posix \
            --enable-libgomp \
            --enable-libssp \
            --enable-libquadmath \
            --enable-lto \
            --enable-shared \
            --disable-multilib
          make -j$JOBS
          make install

      - name: Package toolchain
        run: |
          cd /data/local/tmp
          tar czf gcc15-with-prebuilt-glibc.tar.gz gnu/

      - uses: actions/upload-artifact@v4
        with:
          name: gcc15-with-prebuilt-glibc
          path: /data/local/tmp/gcc15-with-prebuilt-glibc.tar.gz
