name: Build GCC 15 with pre-built glibc & binutils

on:
  workflow_dispatch:
  push:

env:
  PREFIX:   /data/local/tmp/gnu
  SYSROOT:  /data/local/tmp/Android-tools/usr/ld
  TARGET:   aarch64-linux-gnu
  JOBS:     4

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      # 安装编译依赖
      - name: Install build deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential g++ make gawk bison flex texinfo gettext \
            git curl libgmp-dev libmpfr-dev libmpc-dev libisl-dev \
            zlib1g-dev pkg-config python3 \
            linux-libc-dev-arm64-cross lld llvm

      # 准备目录
      - name: Prepare workspace
        run: |
          sudo mkdir -p /data/local/tmp/Android-tools/usr/ld
          sudo chown -R $USER:$USER /data/local/tmp

      # 解压 binutils
      - name: Extract binutils
        run: |
          tar -xzf binutils.tar.gz -C /data/local/tmp/Android-tools/usr/ld --checkpoint=.100

      # 修复点：直接解压glibc，不再创建usr符号链接
      - name: Extract glibc
        run: |
          set -e
          cd /data/local/tmp/Android-tools/usr/ld
          # 直接解压到当前目录
          tar -xzf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ld.tar.gz --checkpoint=.100
          $SYSROOT/aarch64-unknown-linux-gnu/bin/ld --version

      # 软链 kernel headers
      - name: Link kernel headers
        run: |
          K=/usr/aarch64-linux-gnu/include
          [ ! -d "$SYSROOT/usr/include" ] && mkdir -p "$SYSROOT/usr/include"
          ln -sfn "$K/linux"       "$SYSROOT/usr/include/linux"
          ln -sfn "$K/asm"         "$SYSROOT/usr/include/asm"
          ln -sfn "$K/asm-generic" "$SYSROOT/usr/include/asm-generic"

      # 克隆 GCC 15
      - name: Clone GCC
        run: |
          cd /data/local/tmp
          git clone --depth=1 -b master git://gcc.gnu.org/git/gcc.git

      # 配置 & 构建
      - name: Configure GCC
        run: |
          export PATH=$PATH:/data/local/tmp/Android-tools/usr/ld/aarch64-unknown-linux-gnu/bin/
          ld --version
          cd /data/local/tmp
          mkdir build-gcc && cd build-gcc
          ../gcc/configure \
            --prefix="$PREFIX" \
            --target="$TARGET" \
            --with-sysroot="$SYSROOT" \
            --enable-languages=c,c++,lto \
            --enable-threads=posix \
            --enable-libgomp \
            --enable-libssp \
            --enable-libquadmath \
            --enable-lto \
            --disable-multilib \
            --with-newlib \
            --disable-nls \
            --disable-bootstrap \
            --disable-shared \
            --enable-static \
            --with-dynamic-linker=/data/local/tmp/Android-tools/usr/ld/lib/ld-linux-aarch64.so.1

      - name: Build & install
        run: |
          cd /data/local/tmp/build-gcc
          make -j"$JOBS"
          make install

      # 打包 & 上传
      - name: Package toolchain
        run: |
          cd /data/local/tmp
          tar czf gcc15-with-prebuilt-glibc.tar.gz gnu/

      - uses: actions/upload-artifact@v4
        with:
          name: gcc15-with-prebuilt-glibc
          path: /data/local/tmp/gcc15-with-prebuilt-glibc.tar.gz
