name: Build GCC 15 with pre-built glibc

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  PREFIX:   /data/local/tmp/gnu
  SYSROOT:  /data/local/tmp/Android-tools/usr/ld
  TARGET:   aarch64-linux-gnu
  JOBS:     4

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
     - name: Configure & Build GCC  (完全静态)
        run: |
          set -e
          WORK="$HOME/gcc-build"
          rm -rf "$WORK"
          mkdir -p "$WORK" && cd "$WORK"

          # 让 autotools 跳过运行测试
          export lt_cv_sys_max_cmd_len=32768
          export ac_cv_func_malloc_0_nonnull=yes
          export ac_cv_func_realloc_0_nonnull=yes
          export ac_cv_func_calloc_0_nonnull=yes
          export ac_cv_prog_cc_cross=yes
          export cross_compiling=yes
          export cc_cv_works=no

          # 纯静态 build / host / target 三元组一致
          ../gcc/configure \
            --build=aarch64-linux-gnu \
            --host=aarch64-linux-gnu \
            --target=aarch64-linux-gnu \
            --prefix=/data/local/tmp/gnu \
            --with-sysroot=/data/local/tmp/Android-tools/usr/ld \
            --enable-languages=c,c++,lto \
            --enable-static --disable-shared \
            --disable-bootstrap \
            --disable-nls \
            --disable-multilib \
            --with-newlib \
            --disable-libssp \
            --disable-libgomp \
            --disable-libquadmath \
            --enable-threads=posix \
            --with-dynamic-linker='' \
            --disable-sysroot-suffix \
            CFLAGS='-static -Os' \
            CXXFLAGS='-static -Os' \
            LDFLAGS='-static -s'

          make -j"$JOBS" all-gcc
          make install-gcc
