name: Build GCC 15 with pre-built glibc & binutils

on:
  workflow_dispatch:
  push:

env:
  PREFIX:   /data/local/tmp/gnu
  SYSROOT:  /data/local/tmp/Android-tools/usr/ld
  TARGET:   aarch64-linux-gnu
  JOBS:     4

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      #----------------------------------------------------------
      # 1. 安装编译依赖
      #----------------------------------------------------------
      - name: Install build deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential g++ make gawk bison flex texinfo gettext \
            git curl libgmp-dev libmpfr-dev libmpc-dev libisl-dev \
            zlib1g-dev pkg-config python3 \
            linux-libc-dev-arm64-cross lld llvm

      #----------------------------------------------------------
      # 2. 准备目录
      #----------------------------------------------------------
      - name: Prepare workspace
        run: |
          sudo mkdir -p /data/local/tmp/Android-tools/usr/ld
          sudo chown -R $USER:$USER /data/local/tmp

      #----------------------------------------------------------
      # 3. 解压 binutils
      #----------------------------------------------------------
      - name: Extract binutils
        run: |
          tar -xzf binutils.tar.gz -C /data/local/tmp/Android-tools/usr/ld --checkpoint=.100

      #----------------------------------------------------------
      # 4. 解压 glibc（即 ld.tar.gz）
      #----------------------------------------------------------
      - name: Extract glibc
        run: |
          set -e
          ln -s /data/local/tmp/Android-tools/usr/ld/ /data/local/tmp/Android-tools/usr/ld/usr/
          cd /data/local/tmp/Android-tools/usr/ld
          # 如果压缩包里自带 usr/ 就原地展开，否则直接解压
          tar -tzf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ld.tar.gz | head -n1 | grep -q '^usr/' && HAS_USR=1 || HAS_USR=0
          if [ "$HAS_USR" = "1" ]; then
              tar -xzf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ld.tar.gz --checkpoint=.100
          else
              tar -xzf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ld.tar.gz --checkpoint=.100
          fi

      #----------------------------------------------------------
      # 5. 软链 kernel headers
      #----------------------------------------------------------
      - name: Link kernel headers
        run: |
          K=/usr/aarch64-linux-gnu/include
          ln -sfn "$K/linux"       "$SYSROOT/usr/include/linux"
          ln -sfn "$K/asm"         "$SYSROOT/usr/include/asm"
          ln -sfn "$K/asm-generic" "$SYSROOT/usr/include/asm-generic"

      #----------------------------------------------------------
      # 6. 克隆 GCC 15
      #----------------------------------------------------------
      - name: Clone GCC
        run: |
          cd /data/local/tmp
          git clone --depth=1 -b master git://gcc.gnu.org/git/gcc.git

      #----------------------------------------------------------
      # 7. 配置 & 构建
      #----------------------------------------------------------
      - name: Configure GCC
        run: |
          cd /data/local/tmp
          mkdir build-gcc && cd build-gcc
          ../gcc/configure \
            --prefix="$PREFIX" \
            --target="$TARGET" \
            --with-sysroot="$SYSROOT" \
            --with-ld="$SYSROOT/aarch64-unknown-linux-gnu/bin/ld" \
            --enable-languages=c,c++,lto \
            --enable-threads=posix \
            --enable-libgomp \
            --enable-libssp \
            --enable-libquadmath \
            --enable-lto \
            --disable-multilib \
            --with-newlib \
            --disable-nls \
            --disable-bootstrap \
            --disable-shared \
            --enable-static \
            --with-dynamic-linker=/data/local/tmp/Android-tools/usr/ld/lib/ld-linux-aarch64.so.1

      - name: Build & install
        run: |
          cd /data/local/tmp/build-gcc
          make -j"$JOBS"
          make install

      #----------------------------------------------------------
      # 8. 打包 & 上传
      #----------------------------------------------------------
      - name: Package toolchain
        run: |
          cd /data/local/tmp
          tar czf gcc15-with-prebuilt-glibc.tar.gz gnu/

      - uses: actions/upload-artifact@v4
        with:
          name: gcc15-with-prebuilt-glibc
          path: /data/local/tmp/gcc15-with-prebuilt-glibc.tar.gz
